#' Copy a file/object from one stash to another
#'
#' @param file.name Base file name for the object
#' @param from Path for where the object currently resides. Accepts a character
#'    string or *_stash object.
#' @param to Path for where the object will be copied to. Accepts a character
#'    string or *_stash object.
#' @param time.stamp TRUE or FALSE. When TRUE, files containing a time stamp
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    copied.
#' @param uuid TRUE or FALSE. When TRUE, files containing a uuid
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    copied.
#' @param extension Extension for the file to copy.
#' @param compression Accepts NULL for no compression, or 'gz' for gzip.
#' @param checksum Not being used right now.
#' @param keep.from TRUE or FALSE. When TRUE, the files/objects that were
#'    copied from will be deleted.
#' @param clean.up TRUE or FALSE. Only used when \code{keep.from} equals FALSE
#'    When TRUE, and \code{keep.from} equals FALSE, the directory that the file
#'    was copied from will be deleted if it is empty.
#'
#' @return List of stash objects that were successfully copied to their
#'    destination.
#' @export
copy_stash <- function(file.name, from = '', to = '', time.stamp = FALSE,
    uuid = FALSE, extension = NULL, compression = NULL, checksum = FALSE,
    keep.from = TRUE, clean.up = TRUE) {

  from <- as.stash(from)
  to <- as.stash(to)
  copy_stash_(file.name, from, to, time.stamp, uuid, extension, compression,
      checksum, keep.from, clean.up)
}

copy_stash_ <- function(file.name, from, to, time.stamp, uuid, extension,
    compression, checksum, keep.from, clean.up) {

  UseMethod('copy_stash_', from)
}

copy_stash_.local_stash <- function(file.name, from, to, time.stamp, uuid,
    extension, compression, checksum, keep.from, clean.up) {

  UseMethod('copy_stash_.local_stash', to)
}

copy_stash_.s3_stash <- function(file.name, from, to, time.stamp, uuid,
    extension, compression, checksum, keep.from, clean.up) {

  UseMethod('copy_stash_.s3_stash', to)
}
