#' Delete a stashed file
#'
#' @param file.name Base file name for the object
#' @param from Path for where the object resides. Accepts a character
#'    string or *_stash object.
#' @param time.stamp TRUE or FALSE. When TRUE, files containing a time stamp
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    deleted.
#' @param uuid TRUE or FALSE. When TRUE, files containing a uuid
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    deleted.
#' @param extension Extension for the file to delete.
#' @param compression Accepts NULL for no compression, or 'gz' for gzip.
#' @param checksum Not being used right now.
#' @param no.prompt TRUE or FALSE. When FALSE, you will be promted to confirm
#'    deletion of matching files. When TRUE, you will not be prompted. Defaults
#'    to FALSE.
#' @param clean.up TRUE or FALSE. When TRUE, the directory that the file resided
#'    in will be deleted if it is empty.
#'
#' @return List of stash objects that were successfully deleted.
#' @export
delete_stash <- function(file.name, from = '', time.stamp = FALSE, uuid = FALSE,
    extension = NULL, compression = NULL, checksum = FALSE, no.prompt = FALSE,
    clean.up = TRUE) {

  from <- as.stash(from)
  delete_stash_(file.name, from, time.stamp, uuid, extension, compression,
      checksum, no.prompt, clean.up)
}

delete_stash_ <- function(file.name, from, time.stamp, uuid, extension,
    compression, checksum, no.prompt, clean.up) {

  UseMethod('delete_stash_', from)
}