#' Get/Load a stashed object
#'
#' @param file.name Base file name for the object
#' @param from Path for where the object resides. Accepts a character
#'    string or *_stash object.
#' @param time.stamp TRUE or FALSE. When TRUE, files containing a time stamp
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    loaded.
#' @param uuid TRUE or FALSE. When TRUE, files containing a uuid
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    loaded.
#' @param extension Extension for the file to load.
#' @param compression Accepts NULL for no compression, or 'gz' for gzip.
#' @param checksum Not being used right now.
#' @param read.fn Any function where the first argument is the object and the
#'    second is the file path. Will be used to read the files into R.
#' @param ... Arguments to pass to \code{read.fn}.
#'
#' @return List of stash objects that were successfully saved.
#' @export
get_stash <- function(file.name, from = '', time.stamp = FALSE, uuid = FALSE,
    extension = NULL, compression = NULL, checksum = FALSE, read.fn = read.csv,
    ...) {

  from <- as.stash(from)
  get_stash_(file.name, from, time.stamp, uuid, extension, compression,
      checksum, read.fn, ...)
}


get_stash_ <- function(file.name, from, time.stamp, uuid, extension,
    compression, checksum, read.fn, ...) {

  UseMethod('get_stash_', from)
}