#' Move a file/object from one stash to another
#'
#' Same functionality as \code{copy_stash} when \code{keep.stash = TRUE}.
#'
#' @param file.name Base file name for the object
#' @param from Path for where the object currently resides. Accepts a character
#'    string or *_stash object.
#' @param to Path for where the object will be moved to. Accepts a character
#'    string or *_stash object.
#' @param time.stamp TRUE or FALSE. When TRUE, files containing a time stamp
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    moved.
#' @param uuid TRUE or FALSE. When TRUE, files containing a uuid
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    moved.
#' @param extension Extension for the file to copy.
#' @param compression Accepts NULL for no compression, or 'gz' for gzip.
#' @param checksum Not being used right now.
#' @param clean.up TRUE or FALSE. When TRUE, the directory that the file
#'    was moved from will be deleted if it is empty.
#'
#' @return List of stash objects that were successfully moved to their
#'    destination.
#' @export
move_stash <- function(from, to, one.to = 'one', clean.up = TRUE,
    simplify = TRUE) {
  copy_stash(from = from, to = to, one.to = one.to, keep.from = FALSE,
      clean.up = clean.up, simplify = simplify)
}