#' List files/objects that match parameters
#'
#' @param file.name Base file name for the object
#' @param from Path for where the object resides. Accepts a character
#'    string or *_stash object.
#' @param time.stamp TRUE or FALSE. When TRUE, files containing a time stamp
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    matched.
#' @param uuid TRUE or FALSE. When TRUE, files containing a uuid
#'    generated by save_stash, or matching the save_stash pattern, will be
#'    matched.
#' @param extension Extension for the file to load.
#' @param compression Accepts NULL for no compression, or 'gz' for gzip.
#'
#' @return List of stash objects that match parameters.
#' @export
stash_match <- function(file.name, from = '', time.stamp = FALSE, uuid = FALSE,
    extension = NULL, compression = NULL) {

  from <- as.stash(from)
  stash_match_(file.name, from, time.stamp, uuid, extension, compression)
}


stash_match_ <- function(file.name, from, time.stamp, uuid, extension,
    compression, checksum, read.fn, ...) {

  UseMethod('stash_match_', from)
}